# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdwdcfpP-ei_Cvx_0MIiyFPULgwPKulE
"""



from math import cos, sin, pi

length = 50
width = 30
thickness = 10
rotation = 0.15
strands = [0, 2 * pi / 3]
strand_char = "#"

radius = width / 2
for line in range(length):
    output = [" "] * (width + thickness + 2)
    total_rotation = -line * rotation
    sorted_strands = sorted(strands, key=lambda s: cos(total_rotation + s))
    for strand_offset in sorted_strands:
        pos = int(radius * sin(total_rotation + strand_offset) + radius)
        output[pos : pos + thickness + 2] = " " + strand_char * thickness + " "
    print("".join(output))